development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Mixtape Attack
  admin_email: johnhutch+mixtapeadmin@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.mixtape.com
  site_name: Mixtape Attack
  admin_email: johnhutch+mixtapeadmin@gmail.com  
  
production:
  site_url: http://www.mixtape.com
  site_name: Mixtape Attack
  admin_email: johnhutch+mixtapeadmin@gmail.com
