development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Mixtape Attack
  admin_email: johnhutch@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Mixtape Attack
  admin_email: johnhutch@gmail.com  
  
production:
  site_url: http://www.example.com
  site_name: Mixtape Attack
  admin_email: johnhutch@gmail.com
